### ISSUE TITLE
App Crash when scrolling fast on homepage

### ISSUE THREAD

**Issue by DarinMenezes** [danimahardhika/wallpaperboard#4]
02-25 01:40:57.622 12851-12851/com.darin.drisianii E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.darin.drisianii, PID: 12851
                                                                     java.lang.ArrayIndexOutOfBoundsException: length=40; index=-1
                                                                         at java.util.ArrayList.get(ArrayList.java:310)
                                                                         at com.dm.wallpaper.board.adapters.WallpapersAdapter.setFavorite(WallpapersAdapter.java:276)
                                                                         at com.dm.wallpaper.board.adapters.WallpapersAdapter.access$200(WallpapersAdapter.java:72)
                                                                         at com.dm.wallpaper.board.adapters.WallpapersAdapter$1.lambda$onLoadingComplete$0(WallpapersAdapter.java:160)
                                                                         at com.dm.wallpaper.board.adapters.WallpapersAdapter$1$$Lambda$1.onGenerated(Unknown Source)
                                                                         at android.support.v7.graphics.Palette$Builder$1.onPostExecute(Palette.java:873)
                                                                         at android.support.v7.graphics.Palette$Builder$1.onPostExecute(Palette.java:860)
                                                                         at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                         at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7409)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by danimahardhika** [comment]
The issue was similar to this https://github.com/danimahardhika/wallpaperboard/issues/3 and it should be fixed in release [1.0.2](https://github.com/danimahardhika/wallpaperboard/releases/tag/1.0.2)

**Comment by DarinMenezes** [comment]
By when will that launch?

**Comment by danimahardhika** [comment]
Already released https://github.com/danimahardhika/wallpaperboard/releases/tag/1.0.2, just update wallpaperboard from `build.gradle` [How to Update](https://github.com/danimahardhika/wallpaperboard/wiki/How-to-Update)

**Comment by DarinMenezes** [comment]
Thanks! Also a question, how do I change the app version number?

**Comment by danimahardhika** [comment]
Open module:app `build.gradle`, change `versionCode` and `versionName`
